# Generated by Django 4.2.1 on 2023-06-04 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tasks', '0009_alter_task_task_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 16, 27, 35, 72762, tzinfo=datetime.timezone.utc)),
        ),
    ]
